[package]
name = "diesel-concurrency"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.0.0", features = ["postgres", "uuid"] }
diesel_migrations = "2.2.0"
uuid = "1.10.0"
rand = "0.9.0-alpha.2"
